// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OivaTaitoApp.Data;

namespace OivaTaitoApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201109135113_fixed-content")]
    partial class fixedcontent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GoogleId")
                        .HasColumnType("nvarchar(21)")
                        .HasMaxLength(21);

                    b.Property<bool>("initEvalCompleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.EvalFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FeedbackContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<float>("MaxPts")
                        .HasColumnType("real");

                    b.Property<float>("MinPts")
                        .HasColumnType("real");

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionSetId");

                    b.ToTable("EvalFeedbacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FeedbackContent = "Työelämä, joka koostuu yhä useammin projektimuotoisista työtehtävistä, vaatii työntekijöiltä hyviä organisointitaitoja sekä pysymistä tavoitteissa ja dead lineissa. Organisointitaitoja voit parantaa näillä vinkeillä",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 1
                        },
                        new
                        {
                            Id = 2,
                            FeedbackContent = "Olet selvästi jo tottunut organisoimaan työtäsi ja tavoitteellinen työskentely on sinulle tuttua. Voit kuitenkin vielä kehittää itseäsi mm. näillä vinkeillä.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 1
                        },
                        new
                        {
                            Id = 3,
                            FeedbackContent = "Taidat olla ammattilainen organisoinnissa ja tavoitteisiin pääsemisessä. Jos kuitenkin koet, että haluaisit vielä kehittää itseäsi, tsekkaa vinkit täältä.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 1
                        },
                        new
                        {
                            Id = 4,
                            FeedbackContent = "KonMarikin kalpenee sinun organisointitaitojesi rinnalla. Jatka hyvää työtä!",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 1
                        },
                        new
                        {
                            Id = 5,
                            FeedbackContent = "Olet ehkä vasta siirtynyt opiskelemaan korkea-asteelle tai itsenäinen työskentely ei ole sinulle tuttua. Mutta ei hätää, työskentelytaitoja, kuten kaikkia taitoja, voi kehittää. Voit tsekata vinkkejä täältä.",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 6,
                            FeedbackContent = "Taidat jo tuntea itsellesi sopivimmat työskentelytavat ja kykenet itsenäiseen työhön sekä päätöksentekoon. Voit kuitenkin vielä parantaa osaamistasi näissä taidoissa näiden vinkkien avulla.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 7,
                            FeedbackContent = "Olet tottunut tekijä ja ehkä oletkin ollut työelämässä jo useamman vuoden. Aina voi kuitenkin kehittää omaa osaamistaan ja vinkkejä saa täältä.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 8,
                            FeedbackContent = "Olet itsenäinen tehopakkaus, joka saa hommat hoidettua. Hienoa, jatka hyvää työtä.",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 9,
                            FeedbackContent = "Oman työskentelyn johtaminen on yksi tärkeimmistä työelämätaidoista, sillä projektityöt vaativat vastuun ottamista omasta työskentelystä. Myös työyhteisössä toimimisen osaaminen on tärkeää. Olet vasta alussa, mutta voit kehittää itsesi johtamista näillä vinkeillä.",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 10,
                            FeedbackContent = "Osaat jo ottaa vastuuta ja työyhteisösi voi luottaa, että hoidat tehtäväsi kunnialla. Sinulla on kuitenkin vielä kehitettävää itsesi johtamisessa. Katso vinkit täältä.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 11,
                            FeedbackContent = "Olet vastuullinen ja luotettava osa työyhteisöä ja tunnet alasi eettiset periaatteet. Jos kuitenkin koet tarvetta kehittää vielä itseäsi, katso vinkit täältä.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 12,
                            FeedbackContent = "Olet työporukan luottopakki, joka suoriutuu tehtävistä erinomaisesti. Jatka hyvää työtä!",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 13,
                            FeedbackContent = "Tietoa syntyy nopeammin kuin koskaan ennen, jonka takia tiedon hankinta ja analysointitaitojen merkitys vain kasvaa työelämässä. Sinulla on vielä petrattavaa näissä taidoissa, mutta näillä vinkeillä pääset eteenpäin!",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 4
                        },
                        new
                        {
                            Id = 14,
                            FeedbackContent = "Osaat etsiä ja analysoida omaan alaasi liittyvää tietoa, mutta sinulla on vielä kehitettävää. Katso vinkkejä täältä.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 4
                        },
                        new
                        {
                            Id = 15,
                            FeedbackContent = "Olet selvästi edistynyt tiedon hankinta- ja analysointitaidoissa, mutta jos haluat vielä kehittää itseäsi, katso vinkit täältä.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 4
                        },
                        new
                        {
                            Id = 16,
                            FeedbackContent = "Olet tiedon haun Sherlock Holmes! Jatka hyvää työtä!",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 4
                        },
                        new
                        {
                            Id = 17,
                            FeedbackContent = "Viestinnän merkitystä työelämässä ei voi ylikorostaa ja viestintä- ja kommunikaatiotaitojen osaaminen on yleistä työelämäosaamista parhaimmillaan. Olet vielä vasta-alkaja viestinnässä, mutta kehitä taitojasi näiden vinkkien avulla.",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 18,
                            FeedbackContent = "Olet jo jonkin verran kokenut viestijä, mutta osaamisessasi on vielä kehitettävää. Näillä vinkeillä kehität itsestäsi viestinnän ammattilaisen.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 19,
                            FeedbackContent = "Viestit ja kommunikoit sujuvasti sekä suomeksi että vierailla kielillä. Et jännitä vuorovaikutustilanteita tai suoriudut niistä kunnialla läpi. Jos kuitenkin haluat vielä kehittää itseäsi viestijänä, katso nämä vinkit läpi.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 20,
                            FeedbackContent = "Olet viestinnän moniottelija, joka selviää kaikenlaisista vuorovaikutustilanteista ammattilaisen itsevarmuudella. Jatka hyvää työtä!",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 21,
                            FeedbackContent = "Tietoa syntyy nopeammin kuin koskaan ennen, jonka takia tiedon hankinta ja analysointitaitojen merkitys vain kasvaa työelämässä. Sinulla on vielä petrattavaa näissä taidoissa, mutta näillä vinkeillä pääset eteenpäin!",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 22,
                            FeedbackContent = "Osaat etsiä ja analysoida omaan alaasi liittyvää tietoa, mutta sinulla on vielä kehitettävää. Katso vinkkejä täältä.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 23,
                            FeedbackContent = "Olet selvästi edistynyt tiedon hankinta- ja analysointitaidoissa, mutta jos haluat vielä kehittää itseäsi, katso vinkit täältä.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 24,
                            FeedbackContent = "Olet tiedon haun Sherlock Holmes! Jatka hyvää työtä!",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 25,
                            FeedbackContent = "Maailma on täynnä viheliäisiä ongelmia ja työtehtävät keskittyvät entistä enemmän asiakkaiden ongelmien ratkaisuun. Ongelmanratkaisu ja luovuus myös käyvät käsi kädessä. Et ole vielä kokenut ongelmanratkaisija, mutta voit kehittää osaamistasi näillä vinkeillä.",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 26,
                            FeedbackContent = "Olet jo kokenut ongelmanratkaisija ja uskallat luoda uutta. Voit kuitenkin kehittää itseäsi näillä vinkeillä.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 27,
                            FeedbackContent = "Ongelmanratkaisu on sinulle arkipäivää ja keksit luoviakin ratkaisuja viheliäisiin ongelmiin. Jos koet vielä haluavasi kehittää taitojasi, tsekkaa nämä vinkit.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 28,
                            FeedbackContent = "Olet luova ratkaisija, joka tuo oman visionsa esille ja selättää vaikeatkin haasteet. Jatka hyvää työtä!",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 29,
                            FeedbackContent = "Luottamus omaan tekemiseen sekä päätösten teko ja riskien otto kuuluvat osaksi työelämää. Et välttämättä luota vielä omaan osaamiseesi, mutta katso täältä vinkit, joilla voit kehittää näitä taitoja.",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 8
                        },
                        new
                        {
                            Id = 30,
                            FeedbackContent = "Alat tuntea omaa osaamistasi ja uskallat ottaa jonkin verran myös ammatillisia riskejä. Voit kuitenkin vielä kehittyä näissä taidoissa, täältä saat siihen hyviä vinkkejä.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 8
                        },
                        new
                        {
                            Id = 31,
                            FeedbackContent = "Alat olla harjaantunut riskien ottaja ja tiedät oman osaamisesi rajat. Jos haluat vielä kehittää itseäsi, katso täältä vinkit.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 8
                        },
                        new
                        {
                            Id = 32,
                            FeedbackContent = "Tunnet oman osaamisesi kuin omat taskusi eikä riskien ottaminen pelota sinua. Jatka hyvää työtä!",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 8
                        },
                        new
                        {
                            Id = 33,
                            FeedbackContent = "Megatrendit, globaalit ilmiöt ja teknologinen kehitys tulevat mullistamaan yhteiskuntia ja samalla työelämän, joten tulevaisuuteen varautuminen ja tulevaisuustaitojen kehittäminen on tärkeää. Olet vielä vasta-alkaja tulevaisuustaidoissa, mutta voit ottaa osaamista haltuun näillä vinkeillä.",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 9
                        },
                        new
                        {
                            Id = 34,
                            FeedbackContent = "Huomaat omaa alaasi muuttavat tulevaisuustrendit ja osaat jo hiukan ennakoida niitä työsi kannalta. Voit kuitenkin kehittää tulevaisuusosaamistasi vielä lisää näiden vinkkien avulla.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 9
                        },
                        new
                        {
                            Id = 35,
                            FeedbackContent = "Tunnet hyvin alaasi kohtaavia megatrendejä ja millaista osaamista tulevaisuuden työelämä sinulta vaatii. Myös kestävän kehityksen periaatteet ovat sinulle tuttuja. Tulevaisuusosaamista voi kuitenkin vielä kehittää esimerkiksi näiden vinkkien avulla.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 9
                        },
                        new
                        {
                            Id = 36,
                            FeedbackContent = "Pohdit tulevaisuutta viikoittain ja olet varautunut sen mukanaan tuomiin haasteisiin. Omaat hyvät tulevaisuustaidot ja pelon sijaan odotat innolla, mitä tulevaisuus tuo mukanaan.",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 9
                        },
                        new
                        {
                            Id = 37,
                            FeedbackContent = "Ammatillinen verkostoituminen jo opintojen aikana tukee urasuunnittelua ja aktiivinen uratapahtumiin osallistuminen sekä työharjoitteluihin ja opinnäytetyöhön panostaminen auttavat kaikki oman osaamisen tunnistamista ja täten urasuunnittelua. Olet vielä urasi alkutaipaleella, mutta tsekkaa täältä vinkit, kuinka voit tukea omaa uraosaamistasi.",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 38,
                            FeedbackContent = "Olet jo kasvattanut ammatillisia verkostojasi ja sinulle alkaa valjeta, mitä haluat saavuttaa omalla urallasi. Katso täältä vinkit, joilla voit edelleen kehittää osaamistasi.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 39,
                            FeedbackContent = "Urasuunnitelmasi alkavat olla selvillä ja osaat hyödyntää verkostojasi esimerkiksi työnhaussa. Koet varmuuden tunnetta tulevaisuuden urasi suhteen. Vielä voit kuitenkin myös kehittää osaamistasi näillä vinkeillä.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 40,
                            FeedbackContent = "Olet verkostoitumisen ammattilainen ja sinulla on laaja kontaktiverkko, josta saat aina apua urasi kannalta. Jatka hyvää työtä!",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 41,
                            FeedbackContent = "Digityökalut ja työskentely digitaalisessa ympäristössä ovat läsnä kaikissa ammateissa. Siksi on tärkeä omata hyvät ja monipuoliset digitaidot. Olet vielä ehkä hiukan epävarma digikäyttäjä, mutta näillä vinkeillä voit kehittää osaamistasi.",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 42,
                            FeedbackContent = "Digityöskentely alkaa olla sinulle tuttua ja koet olevasi varma peruskäyttäjä. Voit kuitenkin kehittää vielä osaamistasi muun muassa näillä vinkeillä.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 43,
                            FeedbackContent = "Digitaalisuus on sinulle luontevaa ja omaksut uusiakin työkaluja suht nopeasti. Jos koet vielä kehittämisen tarvetta, tsekkaa vinkit täältä.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 44,
                            FeedbackContent = "Olet diginatiivi työntekijä, joka liikkuu sujuvasti alustalta toiselle. Jatka hyvää työtä!",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 45,
                            FeedbackContent = "Monesti tiimityöskentely tai projektityö saattaa tapahtua kansainvälisissä tiimeissä. Siksi toimiminen eri kulttuuri- ja kielitaustoista tulevien ihmisten kanssa on tärkeä taito osata. Olet vielä kansainvälisyytesi alussa, mutta voit kehittää omaa kansainvälisyysosaamistasi näillä vinkeillä.",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 12
                        },
                        new
                        {
                            Id = 46,
                            FeedbackContent = "Sinulla on jo jonkin verran kansainvälisiä tuttavia ja olet ehkä osallistunut johonkin kansainväliseen projektiin. Kansainvälisyydessäsi on kuitenkin vielä potentiaalia kehittyä, joten tsekkaa vinkit täältä.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 12
                        },
                        new
                        {
                            Id = 47,
                            FeedbackContent = "Monikulttuurisuus alkaa olla sinulle tuttua ja osaat toimia hyvin eri taustan omaavien ihmisten kanssa. Jos koet vielä tarvetta kehittää omaa kansainvälisyysosaamistasi, katso vinkit täältä.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 12
                        },
                        new
                        {
                            Id = 48,
                            FeedbackContent = "Olet kansainvälisessä ympäristössä kuin kala vedessä ja osaat toimia useilla eri kielillä monenlaisissa eri projekteissa. Jatka hyvää työtä!",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 12
                        },
                        new
                        {
                            Id = 49,
                            FeedbackContent = "Jotta työtä jaksaa tehdä, myös omasta hyvinvoinnista on huolehdittava. Terveellinen ruokavalio sekä riittävä uni ja liikunta takaavat niin fyysisen kuin psyykkisen jaksamisen työpaikalla. Sinun kannattaisi kiinnittää enemmän huomiota omaan hyvinvointiisi ja priorisoida terveytesi ennen kaikkea.",
                            MaxPts = 2f,
                            MinPts = 0f,
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 50,
                            FeedbackContent = "Tunnistat hyvinvoinnin ja terveyden merkityksen työstä suoriutumisen kannalta. Sinulla on kuitenkin vielä kehitettävää omassa hyvinvoinnissasi. Täältä voit löytää vinkkejä siihen.",
                            MaxPts = 3.5f,
                            MinPts = 2.1f,
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 51,
                            FeedbackContent = "Osaat pitää huolta omasta hyvinvoinnistasi ja ymmärrät priorisoida sitä esimerkiksi töiden edelle. Täältä löydät vielä vinkkejä, jos koet tarvetta kehittää omaa hyvinvointiasi.",
                            MaxPts = 4.5f,
                            MinPts = 3.6f,
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 52,
                            FeedbackContent = "Hyvinvointisi on sinulle ykkösprioriteetti ja myös huolehdit siitä asian vaatimalla tavalla. Jatka hyvää työtä!",
                            MaxPts = 5f,
                            MinPts = 4.6f,
                            QuestionSetId = 13
                        });
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.EvalImprovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImprovementContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("ImprovementVideoUrl")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionSetId");

                    b.ToTable("EvalImprovements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImprovementContent = "Tavoitteellista työskentelyä sekä organisointitaitoja voit kehittää asettamalla itsellesi realistisia tavoitteita opinnoissasi tai työssäsi ja sitoutumalla niihin. Tee aikataulusuunnitelma valmistumiseesi tai jonkin pienemmän projektin ympärille ja pyri pitäytymään tavoitteessasi. Suunnittele myös tehtävämäärän jakautuminen eri päiville, esimerkiksi viikkokalenterin tekeminen aina seuraavaa viikkoa varten auttaa jäsentämään tulevan viikon työmäärää sekä purkaa stressiä, kun olet varautunut etukäteen viikon tapahtumiin. Kun saat jonkin projektin päätökseen, arvioi suoritustasi ja pohdi, mitä olisit voinut / halunnut tehdä toisin ja missä puolestaan onnistuit. Jokainen projekti on arvokas oppimiskokemus ja aikaa kannattaa käyttää myös suorituksen reflektointiin.",
                            ImprovementVideoUrl = "https://www.youtube.com/embed/UFnw4os5HQQ",
                            QuestionSetId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImprovementContent = "Työskentelytaitoja voit kehittää ottamalla osaa erilaisiin aktiviteetteihin. Hyödynnä opintojen aikana mahdollisuudet osallistua tapahtumajärjestämiseen, järjestötoimintaan, projektitöihin tai vaikka hankkeen avustaviin työtehtäviin. Mitä monipuolisempaa kokemusta haalit opintojesi aikana erilaisista töistä, sitä paremmat työskentelyvalmiudet sinulla on työskennellä erilaisissa tehtävissä, erilaisissa organisaatioissa ja erilaisissa tiimeissä. Olemalla avoin, positiivinen ja joustava sopeudut paremmin muutokseen ja erilaisiin työtehtäviin. Työ on paras opettaja kuhunkin työtehtävään, mutta valmiuksia työskennellä eri tavoin on mahdollista kehittää osoittamalla motivaatiota sekä osallistumalla mahdollisimman monenlaisiin projekteihin.",
                            ImprovementVideoUrl = "https://www.youtube.com/embed/3T3VYmro58o",
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 3,
                            ImprovementContent = "Itsensä johtaminen on yksi tärkeimmistä taidoista, joka yksilön tulee osata työelämässä, joka ei kulje enää lineaarista polkua pitkin vaan on pikemminkin verkosto erilaisia mahdollisuuksia. Oman työskentelyn johtamista voi kehittää omien intohimojensa kautta. Mieti, mistä olet intohimoinen ja kulje intohimoasi kohti. Työtehtävät voivat olla hyvinkin erilaisia urasi varrella, mutta löytämällä elämänsä punaisen langan, voi kehittää itseään ja asettaa itselleen tavoitteita, vaikka työnantaja vaihtuisi kahden vuoden välein. Tärkeää on myös osata reflektoida aiemmin koettua ja opittua ja kehittää itseään omien kokemusten kautta. Mitä haluaisit tehdä toisin tai missä olet onnistunut todella hyvin elämäsi aikana? Oman asiantuntijaidentiteetin löytäminen on myös tärkeä osa itsensä johtamista. Kun identiteetti on selvä, on helpompaa myös johtaa itseään. Missä sinä olet asiantuntija tai miltä haluat, että tuleva asiantuntija sinä näyttää?",
                            ImprovementVideoUrl = "https://www.youtube.com/embed/B1NkiFrxctE",
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 4,
                            ImprovementContent = "Tiedon hankintataidot ovat kuin pyörällä ajo, kun sen kerran oppii, sen muistaa lopun ikänsä, mutta ammattilaiseksi voi tulla vain sitkeällä harjoittelulla. Voit kehittää tiedon hankintataitoja kirjoittamalla mahdollisimman paljon ja monenlaisia tekstejä, joissa hyödynnät myös erilaisia lähteitä. Päiväkirja on perinteinen tapa harjoittaa niin kirjoitus- kuin tiedon hankinta- ja analysointitaitoja, mutta voit kokeilla myös pitää asiantuntijablogia, jossa kirjoitat omaan asiantuntijuuteesi liittyvistä teemoista itsellesi mielekkäällä tavalla. Myös raporttien, esseiden ja muiden harjoitustöiden tekeminen kehittää tiedon hankintaa. Voit myös toimia vertaismentorina opiskelukavereillesi tai voitte pitää yhdessä luku- tai kirjoituspiiriä, jossa arvioitte kriittisesti lukemaanne tai kirjoittamaanne. Oman ajatteluhorisontin laajentaminen muiden kanssa kehittää kriittistä ajattelua.",
                            ImprovementVideoUrl = "https://www.youtube.com/embed/3SUWplkXaHI",
                            QuestionSetId = 4
                        },
                        new
                        {
                            Id = 5,
                            ImprovementContent = "Sosiaaliset- sekä yhteistyötaidot korostuvat nykypäivänä entistä enemmän. Tulevalla työpaikallasi voi olla eri kulttuuritaustan omaavia ihmisiä tai voit joutua työskentelemään osana tiimiä, jolloin oman työn tulokset ovat tiimin tuloksia. Tällaisessa työskentelyssä yhteistyötaidot korostuvat ja voit kehittää niitä esimerkiksi osallistumalla erilaisiin projekteihin tai tapahtumajärjestämiseen, joita tehdään usein tiimeissä. Myös vapaaehtoistyö voi auttaa kehittämään yhteistyötaitoja, voit esimerkiksi lähteä ulkomaille kansainväliseen vapaaehtoistyöhön tai toimia Suomessa vapaaehtoisena. Kohtaamalla eri taustoista tulevia ihmisiä ennakkoluulottomasti ja avoimella asenteella, kehität omia yhteistyötaitojasi, mutta saatat myös sattumalta laajentaa elämänpiiriäsi ja saada uusia ystäviä. Aina yhteistyö ei ole kuitenkaan ruusuilla tanssimista ja kannattaakin toimia välillä jossain projektissa tiimin vetäjänä. Jos konflikteja tai ristiriitatilanteita nousee esille, pyri ratkaisemaan ne yhdessä muiden kanssa. Reflektoi myös aiempia tiimityökokemuksiasi ja mieti, mitä olisit voinut tehdä toisin ja missä puolestaan onnistuit mielestäsi hyvin.",
                            ImprovementVideoUrl = "https://www.youtube.com/embed/hjRco3g4trc",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 6,
                            ImprovementContent = "Viestintätaitoja voit kehittää viestimällä. Pidä blogia, osallistu oman alasi seminaareihin tai tapahtumiin, ylläpidä jonkin organisaation some-tiliä tai luo omaa asiantuntijabrändiäsi hyödyntämällä sosiaalista mediaa ja muita työkaluja. Jos teet opinnäytetyötä tai muuta tutkimusta, käy kertomassa ja esitelmöimässä aiheesta. Yleensä oppilaitoksissa on useita mahdollisuuksia päästä esiintymään ja viestimään. Myös tapahtumajärjestäminen on hyvä mahdollisuus kehittää viestintä- ja esiintymistaitoja. Voit vaikka toimia tapahtumajuontajana. Korkeakoulussa viestintä, kommunikaatio- ja esiintymistaitojen kehittämiseen on paljon matalan kynnyksen mahdollisuuksia ja kannattaa yrittää hyödyntää niitä. Kukaan ei ole vakuuttava viestijä tai esiintyjä vaan parhaatkin puhujat ovat tulleet parhaiksi harjoittelemalla ja tekemällä satoja tai jopa tuhansia toistoja. Myös kansainvälisiin seminaareihin tai tapahtumiin kannattaa osallistua, sillä ne antavat mahdollisuuden kehittää viestintätaitoja vierailla kielillä. Oman kielitaidon riittävyyttä ei kannata pelätä, sillä kukaan ei ole täydellinen ja tärkeintä on ymmärretyksi tuleminen.",
                            ImprovementVideoUrl = "https://www.youtube.com/embed/8AxhI4gFCdg",
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 7,
                            ImprovementContent = "Ongelmia ja haasteita on maailma pullollaan. Onkin tärkeää miettiä, miten haasteet ratkaistaan. Ongelmanratkaisutaitoja voit kehittää osallistumalla erilaisiin kehittämishankkeisiin tai esimerkiksi Hackathoneihin, joissa ideana on ratkaista monimutkaisia haasteita monialaisissa tiimeissä. Ongelmia ei kannata pelätä, vaan kannattaa olla oma-aloitteinen ja aktiivinen ja tarttua haasteisiin. Tekemällä jotain asioiden eteen, voi vaikuttaa enemmän kuin ajattelemalla, että joku muu hoitaa. Tässä auttavat myös intohimot. Kun olet intohimoinen jostain asiasta, keskitä energiasi ratkaisemaan haasteita, jotka estävät intohimoasi toteutumasta. Muista, että ei ole yhtä oikeaa ratkaisua vaan ongelmat ovat moniuloitteisia ja ne voidaan ratkaista monella eri tavalla. Tärkeintä on yrittää.",
                            ImprovementVideoUrl = "https://www.youtube.com/embed/TETeXwC6GrM",
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 8,
                            ImprovementContent = "Kun olet muodostanut käsityksen omasta asiantuntijuudestasi ja tunnet oman ammatti-identiteettisi, sinun on helpompi myös ottaa riskejä työelämässä. Jos luotat itseesi ja omiin taitoihisi, myös riskien ottaminen helpottuu. Riskien ottaminen ei kuitenkaan tarkoita elämistä vaaran vyöhykkeellä, vaan sellaisten päätösten tekemistä, joiden takana uskallat seisoa, vaikka muut saattaisivatkin tuomita ideasi. Tärkeintä on, että luotat itseesi. Toki kaikki riskit eivät kannata, mutta koulumaailma antaa hyvät mahdollisuudet harjoittaa riskinottokykyä turvallisessa ympäristössä. Jos saat tehtäväksesi jonkin projektin, tee se täysin uudella tavalla, ja pysy päätöksesi takana. Jos riskin ottaminen ei kannattanut, reflektoi ja mieti, mitä olisit voinut tehdä toisin. Jos projekti taas onnistui, reflektoi kokemusta ja mieti, miten voisit kehittää uuttaa ideaasi edelleen.",
                            ImprovementVideoUrl = "https://www.youtube.com/embed/n9THEiZW0-I",
                            QuestionSetId = 8
                        },
                        new
                        {
                            Id = 9,
                            ImprovementContent = "Maailma muuttuu nopeammin kuin koskaan ennen. Siksi on tärkeää myös ymmärtää tulevaisuutta sekä millaisia taitoja tulevaisuuden ymmärtäminen vaatii. Varaa kalenteristasi joka viikko aikaa noin 10-15 minuuttia, jolloin pohdit tulevaisuutta. Miltä tulevaisuus näyttää, mitä teknologinen kehitys tarkoittaa omalla alallani, millaisia taitoja tarvitsen tulevaisuudessa alallani, mikä vaikutus megatrendeillä (esim. ilmastonmuutos, kaupungistuminen, tekoäly) on omaan uraani, mitä haluan saavuttaa elämässäni pitkällä aikavälillä, missä näen itseni 10, 20 tai 30 vuoden päästä? Tulevaisuudesta on paljon tutkimusta ja sitä on saatavilla esimerkiksi kirjoissa, podcasteissa ja videoissa. Tulevaisuuteen tutustuminen myös hälventää ennakkoluuloja ja pelkoja, joita siihen liittyy ja auttaa sinua varautumaan paremmin tuleviin haasteisiin. Tulevaisuusosaaminen on yksi tulevaisuuden ydinkompetensseista.",
                            ImprovementVideoUrl = "https://www.youtube.com/embed/XsiaeWenc-k",
                            QuestionSetId = 9
                        },
                        new
                        {
                            Id = 10,
                            ImprovementContent = "Urataitoja on helpoin kehittää osallistumalla erilaisiin tapahtumiin sekä verkostoitumalla oman alan ammatti-ihmisten kanssa. Aseta itsellesi tavoitteita omalla urallasi ja pyri niitä kohti. Vaikka työkenttä on pirstaleinen, pidä intohimosi punaisena lankana läpi uran, jolloin oman ammatti-identiteetin kehittäminen on helpompaa. Osallistu alumni- tai mentorointitoimintaan ja keskustele ihmisten kanssa heidän urapoluistaan. Urataidot ovat käytännössä kokoelma kaikkia aiemmin arvioimiasi taitoja ja niiden kaikkien kehittäminen tukee myös omaa urasuunnitteluasi. Mitä monipuolisempi kokemus sinulla on erilaisista työtehtävistä ja -projekteista, sitä paremmat urataidot sinulla on ja olet valmiimpi myös erilaisiin haasteisiin urallasi.",
                            ImprovementVideoUrl = "https://www.youtube.com/embed/nmmpNNqYmU8",
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 11,
                            ImprovementContent = "Digitalisaatio on osa jokaista työpaikkaa jo nyt. Siksi onkin tärkeää omata hyvät digityötaidot. Käytä opintojesi aikana aktiivisesti eri työkaluja ja alustoja, joita sinulla on saatavilla koulusi toimesta. Älä pelkää kokeilla erilaisia sovelluksia ja pyri hyödyntämään mahdollisimman paljon erilaisia digityövälineitä projekteissa. Mitä nopeammin ja helpommin omaksut erilaiset digitaaliset työskentelytavat- ja välineet, sitä helpompaa tuleva työelämä on sinulle. Kartuta myös ymmärrystäsi sellaisista asioista kuin tekoäly tai koodaaminen. Ne tulevat osaltaan vaikuttamaan hyvin paljon tulevaan työelämään ja niiden perusymmärrys helpottaa työskentelyä tulevaisuudessa alalla kuin alalla. Jos oppilaitoksesi järjestää kursseja liittyen teknologiaan tai digitalisaatioon, osallistu niihin, vaikka ne eivät vielä olisikaan alasi kannalta relevantteja. Jo nyt traktori voi hoitaa peltotyöt itsenäisesti GPS-datan avulla tai lääkäri voi pitää etävastaanottoa pienen paikkakunnan terveyskeskuksessa. Se, miten paljon digitalisaatio tulee muokkaamaan yhteiskuntaa, on vasta alkuvaiheessa.",
                            ImprovementVideoUrl = "https://www.youtube.com/embed/p627YgMMMvA",
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 12,
                            ImprovementContent = "Kansainvälisyyttä voit kehittää helposti esimerkiksi lähtemällä vaihtoon opintojesi aikana tai osallistumalla johonkin kansainväliseen projektiin tai hankkeeseen, joita on käynnissä koko ajan kaikissa suomalaisissa korkeakouluissa. Voit myös toimia tuutorina Suomeen saapuville kansainvälisille opiskelijoille, mikä on hyvä mahdollisuus kansainvälistyä, jos sinulla ei ole mahdollisuutta lähteä itse vaihtoon. Voit myös osallistua kansainväliseen vapaaehtoistyöhön, jolloin pääset työskentelemään hyvinkin erilaisista taustoista tulevien ihmisten kanssa. Kannattaa myös osallistua oman alan kansainvälisiin seminaareihin, joissa on mahdollisuus verkostoitua ammatillisesti kansainvälisesti. Omasta kielitaidosta ei kannata kantaa liikaa huolta, sillä tärkeintä on ymmärretyksi tuleminen.",
                            ImprovementVideoUrl = "https://www.youtube.com/embed/DW4Gj2QpRtY",
                            QuestionSetId = 12
                        },
                        new
                        {
                            Id = 13,
                            ImprovementContent = "Voit tutustua aiheeseen lisää päävalikon linkkien kautta.",
                            ImprovementVideoUrl = "",
                            QuestionSetId = 13
                        });
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("QuestionSetId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionSetId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Perehdyn opiskelusuunnitelmani tavoitteisiin",
                            Identifier = "A",
                            QuestionSetId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Asetan työskentelylleni aikataulutavoitteita",
                            Identifier = "B",
                            QuestionSetId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Osaan suunnitella ja aikatauluttaa opintojani",
                            Identifier = "C",
                            QuestionSetId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Saan työni valmiiksi aikataulussa",
                            Identifier = "D",
                            QuestionSetId = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Pystyn selviytymään useasta yhtäaikaisesta opiskelutehtävästä ajallaan",
                            Identifier = "E",
                            QuestionSetId = 1
                        },
                        new
                        {
                            Id = 6,
                            Content = "Haluan oppia oman alani asiantuntijaksi",
                            Identifier = "F",
                            QuestionSetId = 1
                        },
                        new
                        {
                            Id = 7,
                            Content = "Osaan käyttää itselleni sopivimpia työskentelymuotoja",
                            Identifier = "A",
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 8,
                            Content = "Keskityn oppimiseni kannalta tärkeimpiin asioihin",
                            Identifier = "B",
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 9,
                            Content = "Pystyn suunnitelmalliseen ja tavoitteelliseen työskentelyyn",
                            Identifier = "C",
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 10,
                            Content = "Osaan työskennellä joustavasti muuttuvissa tilanteissa",
                            Identifier = "D",
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 11,
                            Content = "Pystyn itsenäiseen kriittiseen ajatteluun",
                            Identifier = "E",
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 12,
                            Content = "Pystyn tekemään itsenäisiä päätöksiä",
                            Identifier = "F",
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 13,
                            Content = "Pystyn suoriutumaan alani käytännön työtehtävistä",
                            Identifier = "G",
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 14,
                            Content = "Osaan arvioida oman toimintani vaikutuksia",
                            Identifier = "H",
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 15,
                            Content = "Siedän haasteita ja muutoksia työskentelyssäni",
                            Identifier = "I",
                            QuestionSetId = 2
                        },
                        new
                        {
                            Id = 16,
                            Content = "Työskentelen omaa alaani kunnioittaen ja olen rehellinen",
                            Identifier = "A",
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 17,
                            Content = "Ymmärrän oman alani eettiset periaatteet",
                            Identifier = "B",
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 18,
                            Content = "Otan vastuun omasta työstäni",
                            Identifier = "C",
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 19,
                            Content = "Huomatessani työhöni/työyhteisööni vaikuttavia epäkohtia, pyrin korjaamaan niitä",
                            Identifier = "D",
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 20,
                            Content = "Työyhteisöni voi luottaa, että teen työni kunnolla",
                            Identifier = "E",
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 21,
                            Content = "Noudatan yhteisiä pelisääntöjä ja sopimuksia",
                            Identifier = "F",
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 22,
                            Content = "Osaan tehdä työni tehokkaasti huomioiden erilaisia näkökulmia",
                            Identifier = "G",
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 23,
                            Content = "Pystyn arvioimaan oman osaamiseni kehittymistä",
                            Identifier = "H",
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 24,
                            Content = "Olen valmis kehittämään itseäni saamani palautteen kautta",
                            Identifier = "I",
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 25,
                            Content = "En lannistu helposti",
                            Identifier = "J",
                            QuestionSetId = 3
                        },
                        new
                        {
                            Id = 26,
                            Content = "Osaan etsiä omaan alaani liittyvää luotettavaa tietoa",
                            Identifier = "A",
                            QuestionSetId = 4
                        },
                        new
                        {
                            Id = 27,
                            Content = "Ymmärrän tekijänoikeudet ja noudatan niitä",
                            Identifier = "B",
                            QuestionSetId = 4
                        },
                        new
                        {
                            Id = 28,
                            Content = "Osaan analysoida ja soveltaa alaani liittyvää tieteellistä tietoa",
                            Identifier = "C",
                            QuestionSetId = 4
                        },
                        new
                        {
                            Id = 29,
                            Content = "Osaan arvioida kriittisesti lähteiden luotettavuutta.",
                            Identifier = "D",
                            QuestionSetId = 4
                        },
                        new
                        {
                            Id = 30,
                            Content = "Tunnen oman alani tärkeimmät toimijat ja seuraan alani kehitystä",
                            Identifier = "E",
                            QuestionSetId = 4
                        },
                        new
                        {
                            Id = 31,
                            Content = "Minulla on hyvät vuorovaikutustaidot",
                            Identifier = "A",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 32,
                            Content = "Osaan työskennellä asiakaslähtöisesti",
                            Identifier = "B",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 33,
                            Content = "Olen empaattinen ja huomioin työyhteisöni jäsenet",
                            Identifier = "C",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 34,
                            Content = "Osaan antaa kehittävää palautetta",
                            Identifier = "D",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 35,
                            Content = "Olen valmis jakamaan osaamistani ja ideoitani tiimissä",
                            Identifier = "E",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 36,
                            Content = "Huolehdin, että tiimin työskentely on tavoitteellista",
                            Identifier = "F",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 37,
                            Content = "Otan huomioon kriittisen ja kehittävän palautteen",
                            Identifier = "G",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 38,
                            Content = "Olen tasapuolinen kaikkia tiimini jäseniä kohtaan",
                            Identifier = "H",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 39,
                            Content = "Kannustan muita tiimini jäseniä yhteisten tavoitteiden saavuttamiseksi",
                            Identifier = "I",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 40,
                            Content = "Pyrin ratkaisemaan tiimityöskentelyyn liittyviä haasteita",
                            Identifier = "J",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 41,
                            Content = "Autan muita tarvittaessa",
                            Identifier = "K",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 42,
                            Content = "Osaan toimia yhteistyössä muiden alojen ammattilaisten kanssa",
                            Identifier = "L",
                            QuestionSetId = 5
                        },
                        new
                        {
                            Id = 43,
                            Content = "Osaan esitellä työni tuloksia ymmärrettävästi",
                            Identifier = "A",
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 44,
                            Content = "Osaan kuvata omaa osaamistani monipuolisesti",
                            Identifier = "B",
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 45,
                            Content = "Osaan viestiä ammatillisesti vieraalla kielellä (a-kieli)",
                            Identifier = "C",
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 46,
                            Content = "Osaan viestiä ammatillisesti toisella kotimaisella kielellä",
                            Identifier = "D",
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 47,
                            Content = "Osaan esiintyä vaikuttavasti",
                            Identifier = "E",
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 48,
                            Content = "Uskallan pitää puoliani sekä perustella näkökantaani",
                            Identifier = "F",
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 49,
                            Content = "Osaan ilmaista itseäni kirjallisesti",
                            Identifier = "G",
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 50,
                            Content = "Osaan suunnitella ja toteuttaa viestintää eri viestintävälineitä hyödyntämällä",
                            Identifier = "H",
                            QuestionSetId = 6
                        },
                        new
                        {
                            Id = 51,
                            Content = "Huomatessani ongelmia pyrin löytämään niihin ratkaisuvaihtoehtoja",
                            Identifier = "A",
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 52,
                            Content = "Olen kriittinen pohtiessani jo olemassa olevien ratkaisujen toimivuutta",
                            Identifier = "B",
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 53,
                            Content = "Osaan ratkaista ammatillisia ongelmia",
                            Identifier = "C",
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 54,
                            Content = "Osaan hyödyntää aiemmin opittua uudessa tilanteessa",
                            Identifier = "D",
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 55,
                            Content = "Olen kekseliäs ja kehitän uusia ideoita",
                            Identifier = "E",
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 56,
                            Content = "Osaan suunnitella ideoistani toimintakelpoisia ratkaisuja",
                            Identifier = "F",
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 57,
                            Content = "Tunnistan mahdollisuuksia, joissa voin laajentaa ammatillisen toimintani rajoja",
                            Identifier = "G",
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 58,
                            Content = "Haluan kehittää omaa alaani",
                            Identifier = "H",
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 59,
                            Content = "Haluan olla innovoimassa oman alani kehittymistä yhteistyössä muiden alojen kanssa",
                            Identifier = "I",
                            QuestionSetId = 7
                        },
                        new
                        {
                            Id = 60,
                            Content = "Uskon omaan tekemiseeni ja uskallan kokeilla vaihtoehtoisia toimintatapoja",
                            Identifier = "A",
                            QuestionSetId = 8
                        },
                        new
                        {
                            Id = 61,
                            Content = "Luotan omaan ammatilliseen osaamiseeni",
                            Identifier = "B",
                            QuestionSetId = 8
                        },
                        new
                        {
                            Id = 62,
                            Content = "Tunnistan alaani liittyviä riskejä",
                            Identifier = "C",
                            QuestionSetId = 8
                        },
                        new
                        {
                            Id = 63,
                            Content = "Toimin alaani liittyvien riskien hallitsemiseksi",
                            Identifier = "D",
                            QuestionSetId = 8
                        },
                        new
                        {
                            Id = 64,
                            Content = "Osaan varautua alani muutoksiin",
                            Identifier = "A",
                            QuestionSetId = 9
                        },
                        new
                        {
                            Id = 65,
                            Content = "Olen kiinnostunut osaamiseni kehittämisestä",
                            Identifier = "B",
                            QuestionSetId = 9
                        },
                        new
                        {
                            Id = 66,
                            Content = "Osaan viedä muutoksia eteenpäin yhteisössäni",
                            Identifier = "C",
                            QuestionSetId = 9
                        },
                        new
                        {
                            Id = 67,
                            Content = "Tunnen kestävän kehityksen periaatteet ja osaan soveltaa niitä alallani",
                            Identifier = "D",
                            QuestionSetId = 9
                        },
                        new
                        {
                            Id = 68,
                            Content = "Osaan tuottaa ymmärrettävää tietoa tulevaisuuden tarpeisiin",
                            Identifier = "E",
                            QuestionSetId = 9
                        },
                        new
                        {
                            Id = 69,
                            Content = "Ymmärrän oman alani osana globaalia maailmaa",
                            Identifier = "F",
                            QuestionSetId = 9
                        },
                        new
                        {
                            Id = 70,
                            Content = "Haluan olla vaikuttamassa oman alani kehittämiseen osana muuta yhteiskunnallista kehitystä",
                            Identifier = "G",
                            QuestionSetId = 9
                        },
                        new
                        {
                            Id = 71,
                            Content = "Kehitän omaa ammatillista osaamistani työharjoitteluiden tai työkokemuksen kautta",
                            Identifier = "A",
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 72,
                            Content = "Kasvatan ammatillisia verkostojani jo opintojeni aikana",
                            Identifier = "B",
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 73,
                            Content = "Opinnäytetyöni tukee ammatillista kehittymistäni",
                            Identifier = "C",
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 74,
                            Content = "Tunnistan osaamiseni ja osaan hakea sitä vastaavia työtehtäviä",
                            Identifier = "D",
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 75,
                            Content = "Osaan projektien hallintaa ja hyödyntää siihen kuuluvia työkaluja",
                            Identifier = "E",
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 76,
                            Content = "Osaan kehittää, organisoida ja hallita omaa liiketoimintaa",
                            Identifier = "F",
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 77,
                            Content = "Asetan uratavoitteita ja pyrin niitä kohti",
                            Identifier = "G",
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 78,
                            Content = "Kehitän työelämätaitojani",
                            Identifier = "H",
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 79,
                            Content = "Seuraan oman alani ja osaamiseeni liittyviä työmahdollisuuksia aktiivisesti",
                            Identifier = "I",
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 80,
                            Content = "Osallistun oman alan tapahtumiin ja seminaareihin",
                            Identifier = "J",
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 81,
                            Content = "Ennakoin urallani kohtaamiani muutoksia",
                            Identifier = "K",
                            QuestionSetId = 10
                        },
                        new
                        {
                            Id = 82,
                            Content = "Osaan käyttää oman alani kannalta keskeisiä digitaalisia työkaluja",
                            Identifier = "A",
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 83,
                            Content = "Osaan käsitellä oman alani dataa",
                            Identifier = "B",
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 84,
                            Content = "Osaan suojata oman digitaalisen identiteettini",
                            Identifier = "C",
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 85,
                            Content = "Osaan luoda ja jakaa digitaalisia sisältöjä",
                            Identifier = "D",
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 86,
                            Content = "Osaan käyttää digitaalisia työkaluja yhteistyöhön ja viestintään",
                            Identifier = "E",
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 87,
                            Content = "Osaan toimia turvallisesti digitaalisissa ympäristöissä",
                            Identifier = "F",
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 88,
                            Content = "Osaan toimia digitaalisessa ympäristössä toisia kunnioittaen",
                            Identifier = "G",
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 89,
                            Content = "Osaan arvioida kriittisesti digitaalisten sisältöjen luotettavuutta",
                            Identifier = "H",
                            QuestionSetId = 11
                        },
                        new
                        {
                            Id = 90,
                            Content = "Ymmärrän erilaisia kulttuuritaustoja ja osaan huomioida niiden merkitystä vuorovaikutuksessa",
                            Identifier = "A",
                            QuestionSetId = 12
                        },
                        new
                        {
                            Id = 91,
                            Content = "Osaan toimia monikulttuurisessa ympäristössä toisia kunnioittavasti",
                            Identifier = "B",
                            QuestionSetId = 12
                        },
                        new
                        {
                            Id = 92,
                            Content = "Tunnistan alani kansainväliset verkostot.",
                            Identifier = "C",
                            QuestionSetId = 12
                        },
                        new
                        {
                            Id = 93,
                            Content = "Kasvatan ammatillista verkostoani kansainvälisesti",
                            Identifier = "D",
                            QuestionSetId = 12
                        },
                        new
                        {
                            Id = 94,
                            Content = "Osaan toimia monenlaisissa yhteisöissä riippumatta sijainnista tai kielestä",
                            Identifier = "E",
                            QuestionSetId = 12
                        },
                        new
                        {
                            Id = 95,
                            Content = "Seuraan globaalia mediaa",
                            Identifier = "F",
                            QuestionSetId = 12
                        },
                        new
                        {
                            Id = 96,
                            Content = "Pidän huolta fyysisestä kunnostani",
                            Identifier = "A",
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 97,
                            Content = "Lepään ja nukun tarpeeksi",
                            Identifier = "B",
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 98,
                            Content = "Syön terveellisesti",
                            Identifier = "C",
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 99,
                            Content = "Minulla on läheisiä ihmissuhteita ja varaan niille aikaa",
                            Identifier = "D",
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 100,
                            Content = "Koen onnistumisen tunteita",
                            Identifier = "E",
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 101,
                            Content = "Koen olevani hyväksytty",
                            Identifier = "F",
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 102,
                            Content = "Vietän mielekästä vapaa-aikaa ja rentoudun minulle tärkeiden asioiden parissa",
                            Identifier = "G",
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 103,
                            Content = "Olen oma-aloitteinen",
                            Identifier = "H",
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 104,
                            Content = "Otan vastuuta tekemisistäni",
                            Identifier = "I",
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 105,
                            Content = "Luotan itseeni alani osaajana",
                            Identifier = "J",
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 106,
                            Content = "Pystyn suoriutumaan työtehtävistäni paineen alla",
                            Identifier = "K",
                            QuestionSetId = 13
                        },
                        new
                        {
                            Id = 107,
                            Content = "Tiedän, mistä voin tarvittaessa kysyä ja saada apua",
                            Identifier = "L",
                            QuestionSetId = 13
                        });
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.QuestionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ColorHex")
                        .HasColumnType("nvarchar(6)")
                        .HasMaxLength(6);

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.ToTable("QuestionCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "00C9B8",
                            Identifier = "A",
                            Title = "Oman osaamisen kehittäminen ja johtaminen"
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "FCD200",
                            Identifier = "B",
                            Title = "Tiedon hankinta ja analysointi"
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "66C46D",
                            Identifier = "C",
                            Title = "Yhteistyötaidot ja viestintä"
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "FE5E54",
                            Identifier = "D",
                            Title = "Innovointi ja luova ongelmanratkaisu"
                        },
                        new
                        {
                            Id = 5,
                            ColorHex = "FFB3C1",
                            Identifier = "E",
                            Title = "Tulevaisuustaidot: urasuunnittelu, yrittäjyys, digitaalisuus, monikulttuurisuus, kestävä kehitys"
                        },
                        new
                        {
                            Id = 6,
                            ColorHex = "519cd2",
                            Identifier = "F",
                            Title = "Itseluottamus ja hyvinvointi työssä"
                        });
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.QuestionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("QuestionCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("Id");

                    b.HasIndex("QuestionCategoryId");

                    b.ToTable("QuestionSets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Identifier = "1",
                            QuestionCategoryId = 1,
                            Title = "Tavoitteellinen työskentely ja organisointitaidot"
                        },
                        new
                        {
                            Id = 2,
                            Identifier = "2",
                            QuestionCategoryId = 1,
                            Title = "Työskentelytaidot"
                        },
                        new
                        {
                            Id = 3,
                            Identifier = "3",
                            QuestionCategoryId = 1,
                            Title = "Oman työskentelyn johtaminen"
                        },
                        new
                        {
                            Id = 4,
                            Identifier = "1",
                            QuestionCategoryId = 2,
                            Title = "Tiedon hankinta ja analysointi"
                        },
                        new
                        {
                            Id = 5,
                            Identifier = "1",
                            QuestionCategoryId = 3,
                            Title = "Yhteistyötaidot"
                        },
                        new
                        {
                            Id = 6,
                            Identifier = "2",
                            QuestionCategoryId = 3,
                            Title = "Viestintä- ja kommunikaatiotaidot"
                        },
                        new
                        {
                            Id = 7,
                            Identifier = "1",
                            QuestionCategoryId = 4,
                            Title = "Ongelmanratkaisutaidot ja innovointi"
                        },
                        new
                        {
                            Id = 8,
                            Identifier = "2",
                            QuestionCategoryId = 4,
                            Title = "Riskinottokyky / Riskien hallinta"
                        },
                        new
                        {
                            Id = 9,
                            Identifier = "1",
                            QuestionCategoryId = 5,
                            Title = "Tulevaisuustaidot"
                        },
                        new
                        {
                            Id = 10,
                            Identifier = "2",
                            QuestionCategoryId = 5,
                            Title = "Urataidot"
                        },
                        new
                        {
                            Id = 11,
                            Identifier = "3",
                            QuestionCategoryId = 5,
                            Title = "Digitaaliset työskentelytaidot"
                        },
                        new
                        {
                            Id = 12,
                            Identifier = "4",
                            QuestionCategoryId = 5,
                            Title = "Kansainvälisyys"
                        },
                        new
                        {
                            Id = 13,
                            Identifier = "1",
                            QuestionCategoryId = 6,
                            Title = "Itseluottamus ja hyvinvointi työssä"
                        });
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.SelfEvalResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Answer")
                        .HasColumnType("real");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("SelfEvaluationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelfEvaluationId");

                    b.ToTable("SelfEvalResults");
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.SelfEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EvaluatorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatorId");

                    b.ToTable("SelfEvaluations");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.EvalFeedback", b =>
                {
                    b.HasOne("OivaTaitoApp.Data.Models.QuestionSet", "QuestionSet")
                        .WithMany()
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.EvalImprovement", b =>
                {
                    b.HasOne("OivaTaitoApp.Data.Models.QuestionSet", "QuestionSet")
                        .WithMany()
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.Question", b =>
                {
                    b.HasOne("OivaTaitoApp.Data.Models.QuestionSet", "QuestionSet")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.QuestionSet", b =>
                {
                    b.HasOne("OivaTaitoApp.Data.Models.QuestionCategory", "QuestionCategory")
                        .WithMany("QuestionSets")
                        .HasForeignKey("QuestionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.SelfEvalResult", b =>
                {
                    b.HasOne("OivaTaitoApp.Data.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OivaTaitoApp.Data.Models.SelfEvaluation", "SelfEvaluation")
                        .WithMany("SelfEvalResults")
                        .HasForeignKey("SelfEvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OivaTaitoApp.Data.Models.SelfEvaluation", b =>
                {
                    b.HasOne("OivaTaitoApp.Data.Models.AppUser", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
